runtime: python
env: flex
service: app2-service  

runtime_config:
  # Latest supported Python version
  runtime_version: "3.13"
  # OS for the runtime
  operating_system: "ubuntu22"

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Optional: environment variables
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "gcloud_creds.json"
  PROJECT: "examples-471711"
